version: 0.2

phases:
  install:
    on-failure: ABORT | CONTINUE
    runtime-versions:
      runtime: 
        nodejs: 12
    commands:
      - npm ci
  pre_build:
    # on-failure: ABORT | CONTINUE
    # commands:
    #   - command
    #   - command
    # finally:
    #   - command
    #   - command
  build:
    # on-failure: ABORT | CONTINUE
    # commands:
    #   - command
    #   - command
    # finally:
    #   - command
    #   - command
  post_build:
    # on-failure: ABORT | CONTINUE
    # commands:
    #   - command
    #   - command
    # finally:
    #   - command
    #   - command
