version: 0.2

phases:
  install:
    on-failure: ABORT | CONTINUE
    runtime-versions:
      runtime: 
        nodejs: 12
    commands:
      - npm ci
  pre_build:
    # on-failure: ABORT | CONTINUE
    commands:
      - echo 'This phease is pre_build'
    #   - command
    # finally:
    #   - command
    #   - command
  build:
    # on-failure: ABORT | CONTINUE
    commands:
      - echo 'This phease is build'
    #   - command
    # finally:
    #   - command
    #   - command
  post_build:
    # on-failure: ABORT | CONTINUE
    commands:
      - echo 'This phease is post_build'
    #   - command
    # finally:
    #   - command
    #   - command
