version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  pre_build:
    commands:
      - echo 'This phease is pre_build'
    #   - command
    # finally:
    #   - command
    #   - command
  build:
    commands:
      - echo 'This phease is build'
    #   - command
    # finally:
    #   - command
    #   - command
  post_build:
    commands:
      - echo This phease is post_build at `date`
      - echo exec DB migration
      - npm run db:migrate
    # finally:
    #   - command
    #   - command
